# Generated by Django 4.2.20 on 2025-03-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='quantidade_pessoas',
            field=models.IntegerField(default=1),
        ),
    ]
