# Generated by Django 4.2.20 on 2025-03-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_alter_agendamento_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='quantidade_pessoas',
            new_name='quantidade_adultos',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='nome_passageiro',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='numero_voo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='quantidade_criancas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='telefone_contato',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='tipo_servico',
            field=models.CharField(choices=[('TRANSFER', 'Transfer'), ('PASSEIO', 'Passeio')], default='TRANSFER', max_length=20),
        ),
    ]
